export const defaultExercises = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/I-Of0Ev43i4Zt7",
    id: "0002",
    instructions: [
      "Stand with your feet shoulder-width apart and your arms extended straight down by your sides.",
      "Keeping your back straight and your core engaged, …o one side, lowering your hand towards your knee.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat on the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
    name: "45° side bend",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/vKAWsPzehvwbAa",
    id: "1512",
    instructions: [
      "Start on all fours with your hands directly under …houlders and your knees directly under your hips.",
      "Extend one leg straight back, keeping your knee bent and your foot flexed.",
      "Slowly lower your hips towards the ground, feeling a stretch in your quads.",
      "Hold this position for 20-30 seconds.",
      "Switch legs and repeat the stretch on the other side.",
    ],
    name: "all fours squad stretch",
    target: "quads",
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "https://v2.exercisedb.io/image/I4XMjCBFhqaGoJ",
    id: "0007",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, th…elease the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "alternate lateral pulldown",
    target: "lats",
  },
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/-EA4vBhetgIhoR",
    id: "1368",
    instructions: [
      "Sit on the ground with your legs extended in front of you.",
      "Lift one leg off the ground and rotate your ankle in a circular motion.",
      "Perform the desired number of circles in one direction, then switch to the other direction.",
      "Repeat with the other leg.",
    ],
    name: "ankle circles",
    target: "calves",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/Bi8xVYeWIyqo56",
    id: "3294",
    instructions: [
      "Start in a push-up position with your hands slightly wider than shoulder-width apart.",
      "Extend one arm straight out to the side, parallel to the ground.",
      "Lower your body by bending your elbows, keeping your back straight and core engaged.",
      "Push back up to the starting position.",
      "Repeat on the other side, extending the opposite arm out to the side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
    name: "archer push up",
    target: "pectorals",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/Y99VpeCGG19urP",
    id: "0006",
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms straight out to the sides, parallel to the ground.",
      "Engaging your abs, lift your shoulders off the gro…nd reach your right hand towards your right heel.",
      "Return to the starting position and repeat on the …, reaching your left hand towards your left heel.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
    name: "alternate heel touchers",
    target: "abs",
  },
];
